/* calltable.h - generated by make-header.py; do not modify! */

#ifndef __CALLTABLE_H
#define __CALLTABLE_H

#include <arch/sched_asm_inserts.h>
K_CALL_DEFINE_1_1 (X_malloc);
K_CALL_DEFINE_1_0 (X_mrelease);
K_CALL_DEFINE_3_0 (Y_in);
K_CALL_DEFINE_3_0 (Y_out);
K_CALL_DEFINE_2_1 (X_mt_alloc);
K_CALL_DEFINE_1_1 (X_mt_clone);
K_CALL_DEFINE_1_0 (X_mt_release);
K_CALL_DEFINE_2_0 (Y_in32);
K_CALL_DEFINE_2_0 (Y_in8);
K_CALL_DEFINE_2_0 (Y_mt_in);
K_CALL_DEFINE_2_0 (Y_mt_out);
K_CALL_DEFINE_2_0 (Y_mt_xchg);
K_CALL_DEFINE_2_0 (Y_mt_xin);
K_CALL_DEFINE_2_0 (Y_mt_xout);
K_CALL_DEFINE_2_0 (Y_mt_xxchg);
K_CALL_DEFINE_2_0 (Y_out32);
K_CALL_DEFINE_2_0 (Y_out8);
K_CALL_DEFINE_2_0 (Y_outbyte);
K_CALL_DEFINE_2_0 (Y_outword);
K_CALL_DEFINE_2_0 (X_fbar_enroll);
K_CALL_DEFINE_1_0 (X_fbar_init);
K_CALL_DEFINE_2_0 (X_fbar_resign);
K_CALL_DEFINE_0_1 (X_ldtimer);
K_CALL_DEFINE_2_0 (X_mt_unlock);
K_CALL_DEFINE_2_1 (X_proc_alloc);
K_CALL_DEFINE_3_0 (X_proc_mt_copy);
K_CALL_DEFINE_3_0 (X_proc_mt_move);
K_CALL_DEFINE_3_0 (X_proc_param);
K_CALL_DEFINE_1_0 (X_sem_release);
K_CALL_DEFINE_1_0 (Y_endp);
K_CALL_DEFINE_1_0 (Y_fbar_sync);
K_CALL_DEFINE_1_0 (Y_mreleasep);
K_CALL_DEFINE_2_0 (Y_mt_lock);
K_CALL_DEFINE_1_0 (Y_mt_sync);
K_CALL_DEFINE_1_0 (Y_proc_end);
K_CALL_DEFINE_3_0 (Y_proc_start);
K_CALL_DEFINE_1_0 (Y_sem_claim);
K_CALL_DEFINE_2_0 (Y_startp);
K_CALL_DEFINE_3_0 (Y_xin);
K_CALL_DEFINE_2_1 (X_cdisc);
K_CALL_DEFINE_2_1 (X_cenbc);
K_CALL_DEFINE_3_1 (X_disc);
K_CALL_DEFINE_2_1 (X_enbc);
K_CALL_DEFINE_0_1 (X_getpas);
K_CALL_DEFINE_2_0 (X_mt_enroll);
K_CALL_DEFINE_2_0 (X_mt_resign);
K_CALL_DEFINE_3_1 (X_ndisc);
K_CALL_DEFINE_1_0 (X_runp);
K_CALL_DEFINE_2_0 (Y_enbc2);
K_CALL_DEFINE_3_1 (Y_enbc3);
K_CALL_DEFINE_1_0 (Y_fasttin);
K_CALL_DEFINE_0_0 (Y_pause);
K_CALL_DEFINE_0_0 (Y_stopp);
K_CALL_DEFINE_1_0 (Y_tin);
K_CALL_DEFINE_0_0 (X_alt);
K_CALL_DEFINE_2_1 (X_cdist);
K_CALL_DEFINE_2_1 (X_cenbt);
K_CALL_DEFINE_3_1 (X_dist);
K_CALL_DEFINE_2_1 (X_enbt);
K_CALL_DEFINE_3_1 (X_ndist);
K_CALL_DEFINE_1_0 (X_sem_init);
K_CALL_DEFINE_0_0 (X_talt);
K_CALL_DEFINE_1_0 (X_xend);
K_CALL_DEFINE_0_0 (Y_altend);
K_CALL_DEFINE_0_0 (Y_altwt);
K_CALL_DEFINE_0_0 (Y_caltend);
K_CALL_DEFINE_2_0 (Y_enbt2);
K_CALL_DEFINE_3_1 (Y_enbt3);
K_CALL_DEFINE_0_0 (Y_taltwt);
K_CALL_DEFINE_1_0 (Y_xable);
K_CALL_DEFINE_1_1 (X_cdiss);
K_CALL_DEFINE_1_1 (X_cenbs);
K_CALL_DEFINE_2_1 (X_diss);
K_CALL_DEFINE_1_1 (X_enbs);
K_CALL_DEFINE_3_1 (X_mt_dclone);
K_CALL_DEFINE_2_1 (X_ndiss);
K_CALL_DEFINE_1_0 (Y_enbs2);
K_CALL_DEFINE_2_1 (Y_enbs3);
K_CALL_DEFINE_2_1 (X_fmul);
K_CALL_DEFINE_1_0 (X_kernel_run);
K_CALL_DEFINE_3_1 (X_mt_bind);
K_CALL_DEFINE_3_1 (X_mt_resize);
K_CALL_DEFINE_2_3 (X_norm);
K_CALL_DEFINE_2_0 (X_par_enroll);
K_CALL_DEFINE_0_0 (Y_fastscheduler);
K_CALL_DEFINE_0_0 (Y_occscheduler);
K_CALL_DEFINE_0_1 (X_getaff);
K_CALL_DEFINE_0_1 (X_getpri);
K_CALL_DEFINE_1_0 (Y_setaff);
K_CALL_DEFINE_1_0 (Y_setpri);
K_CALL_DEFINE_1_1 (X_bx_kill);
K_CALL_DEFINE_1_1 (X_mppclone);
K_CALL_DEFINE_2_0 (Y_b_dispatch);
K_CALL_DEFINE_2_0 (Y_bx_dispatch);
K_CALL_DEFINE_3_0 (Y_mppdeserialise);
K_CALL_DEFINE_3_0 (Y_mppserialise);
K_CALL_DEFINE_1_0 (Y_rtthreadinit);
K_CALL_DEFINE_0_0 (Y_shutdown);
static void *kernel_CIF_endp_resume_stub (void);
static void *kernel_CIF_light_proc_stub (void);
static void *kernel_CIF_proc_stub (void);
K_CALL_DEFINE_2_0 (X_ldwsmap);
K_CALL_DEFINE_1_0 (X_rmwsmap);
K_CALL_DEFINE_3_3 (X_trap);
K_CALL_DEFINE_2_0 (X_ulwsmap);
K_CALL_DEFINE_0_0 (Y_BNSeterr);
K_CALL_DEFINE_0_0 (Y_BSeterr);
K_CALL_DEFINE_0_0 (Y_BasicRangeError);
K_CALL_DEFINE_4_0 (Y_RangeCheckError);
K_CALL_DEFINE_4_0 (Y_Seterr);
K_CALL_DEFINE_0_0 (Y_dynproc_exit);
K_CALL_DEFINE_1_0 (Y_dynproc_suspend);
K_CALL_DEFINE_5_0 (Y_floaterr);
K_CALL_DEFINE_4_0 (Y_overflow);
K_CALL_DEFINE_0_0 (Y_unsupported);
K_CALL_DEFINE_4_0 (Y_zero_div);

#ifdef CCSP_DIRECT_CALL
#if defined(__aarch64__) || defined(_M_ARM64)
/* AArch64 assembly adapters: tail-call to preserve x30 for rescheduling. */
/* Old ABI: (param0=x0, sched=x1, Wptr=x2) + sched->cparam[] */
/* New ABI: (p0=x0, p1=x1, ..., sched=xN, Wptr=xN+1) */
static void __attribute__((naked)) calltable_adapter_X_malloc(void) {
	__asm__ volatile (
		"b kernel_X_malloc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mrelease(void) {
	__asm__ volatile (
		"b kernel_X_mrelease\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_in(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_in\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_out(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_out\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_alloc(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_mt_alloc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_clone(void) {
	__asm__ volatile (
		"b kernel_X_mt_clone\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_release(void) {
	__asm__ volatile (
		"b kernel_X_mt_release\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_in32(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_in32\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_in8(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_in8\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_in(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_mt_in\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_out(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_mt_out\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_xchg(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_mt_xchg\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_xin(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_mt_xin\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_xout(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_mt_xout\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_xxchg(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_mt_xxchg\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_out32(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_out32\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_out8(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_out8\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_outbyte(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_outbyte\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_outword(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_outword\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_fbar_enroll(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_fbar_enroll\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_fbar_init(void) {
	__asm__ volatile (
		"b kernel_X_fbar_init\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_fbar_resign(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_fbar_resign\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_ldtimer(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_X_ldtimer\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_unlock(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_mt_unlock\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_proc_alloc(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_proc_alloc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_proc_mt_copy(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_proc_mt_copy\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_proc_mt_move(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_proc_mt_move\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_proc_param(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_proc_param\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_sem_release(void) {
	__asm__ volatile (
		"b kernel_X_sem_release\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_endp(void) {
	__asm__ volatile (
		"b kernel_Y_endp\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_fbar_sync(void) {
	__asm__ volatile (
		"b kernel_Y_fbar_sync\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mreleasep(void) {
	__asm__ volatile (
		"b kernel_Y_mreleasep\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_lock(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_mt_lock\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mt_sync(void) {
	__asm__ volatile (
		"b kernel_Y_mt_sync\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_proc_end(void) {
	__asm__ volatile (
		"b kernel_Y_proc_end\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_proc_start(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_proc_start\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_sem_claim(void) {
	__asm__ volatile (
		"b kernel_Y_sem_claim\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_startp(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_startp\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_xin(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_xin\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_cdisc(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_cdisc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_cenbc(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_cenbc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_disc(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_disc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_enbc(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_enbc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_getpas(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_X_getpas\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_enroll(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_mt_enroll\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_resign(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_mt_resign\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_ndisc(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_ndisc\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_runp(void) {
	__asm__ volatile (
		"b kernel_X_runp\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_enbc2(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_enbc2\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_enbc3(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_enbc3\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_fasttin(void) {
	__asm__ volatile (
		"b kernel_Y_fasttin\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_pause(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_pause\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_stopp(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_stopp\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_tin(void) {
	__asm__ volatile (
		"b kernel_Y_tin\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_alt(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_X_alt\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_cdist(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_cdist\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_cenbt(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_cenbt\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_dist(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_dist\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_enbt(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_enbt\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_ndist(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_ndist\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_sem_init(void) {
	__asm__ volatile (
		"b kernel_X_sem_init\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_talt(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_X_talt\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_xend(void) {
	__asm__ volatile (
		"b kernel_X_xend\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_altend(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_altend\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_altwt(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_altwt\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_caltend(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_caltend\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_enbt2(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_enbt2\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_enbt3(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_enbt3\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_taltwt(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_taltwt\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_xable(void) {
	__asm__ volatile (
		"b kernel_Y_xable\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_cdiss(void) {
	__asm__ volatile (
		"b kernel_X_cdiss\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_cenbs(void) {
	__asm__ volatile (
		"b kernel_X_cenbs\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_diss(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_diss\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_enbs(void) {
	__asm__ volatile (
		"b kernel_X_enbs\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_dclone(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_mt_dclone\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_ndiss(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_ndiss\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_enbs2(void) {
	__asm__ volatile (
		"b kernel_Y_enbs2\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_enbs3(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_enbs3\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_fmul(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_fmul\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_kernel_run(void) {
	__asm__ volatile (
		"b kernel_X_kernel_run\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_bind(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_mt_bind\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mt_resize(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_mt_resize\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_norm(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_norm\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_par_enroll(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_par_enroll\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_fastscheduler(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_fastscheduler\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_occscheduler(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_occscheduler\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_getaff(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_X_getaff\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_getpri(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_X_getpri\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_setaff(void) {
	__asm__ volatile (
		"b kernel_Y_setaff\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_setpri(void) {
	__asm__ volatile (
		"b kernel_Y_setpri\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_bx_kill(void) {
	__asm__ volatile (
		"b kernel_X_bx_kill\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_mppclone(void) {
	__asm__ volatile (
		"b kernel_X_mppclone\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_b_dispatch(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_b_dispatch\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_bx_dispatch(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_Y_bx_dispatch\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mppdeserialise(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_mppdeserialise\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_mppserialise(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_Y_mppserialise\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_rtthreadinit(void) {
	__asm__ volatile (
		"b kernel_Y_rtthreadinit\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_shutdown(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_shutdown\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_ldwsmap(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_ldwsmap\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_rmwsmap(void) {
	__asm__ volatile (
		"b kernel_X_rmwsmap\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_trap(void) {
	__asm__ volatile (
		"mov x4, x2\n\t"          /* x4 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = sched->cparam[1] */
		"mov x3, x1\n\t"          /* x3 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"b kernel_X_trap\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_X_ulwsmap(void) {
	__asm__ volatile (
		"mov x3, x2\n\t"          /* x3 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = sched->cparam[0] */
		"mov x2, x1\n\t"          /* x2 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"b kernel_X_ulwsmap\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_BNSeterr(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_BNSeterr\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_BSeterr(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_BSeterr\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_BasicRangeError(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_BasicRangeError\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_RangeCheckError(void) {
	__asm__ volatile (
		"mov x5, x2\n\t"          /* x5 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = cparam[1] */
		"ldr x11, [x1, #24]\n\t"  /* x11 = cparam[2] */
		"mov x4, x1\n\t"          /* x4 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"mov x3, x11\n\t"         /* x3 = cparam[2] */
		"b kernel_Y_RangeCheckError\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_Seterr(void) {
	__asm__ volatile (
		"mov x5, x2\n\t"          /* x5 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = cparam[1] */
		"ldr x11, [x1, #24]\n\t"  /* x11 = cparam[2] */
		"mov x4, x1\n\t"          /* x4 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"mov x3, x11\n\t"         /* x3 = cparam[2] */
		"b kernel_Y_Seterr\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_dynproc_exit(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_dynproc_exit\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_dynproc_suspend(void) {
	__asm__ volatile (
		"b kernel_Y_dynproc_suspend\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_floaterr(void) {
	__asm__ volatile (
		"mov x6, x2\n\t"          /* x6 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = cparam[1] */
		"ldr x11, [x1, #24]\n\t"  /* x11 = cparam[2] */
		"ldr x12, [x1, #32]\n\t"  /* x12 = cparam[3] */
		"mov x5, x1\n\t"          /* x5 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"mov x3, x11\n\t"         /* x3 = cparam[2] */
		"mov x4, x12\n\t"         /* x4 = cparam[3] */
		"b kernel_Y_floaterr\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_overflow(void) {
	__asm__ volatile (
		"mov x5, x2\n\t"          /* x5 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = cparam[1] */
		"ldr x11, [x1, #24]\n\t"  /* x11 = cparam[2] */
		"mov x4, x1\n\t"          /* x4 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"mov x3, x11\n\t"         /* x3 = cparam[2] */
		"b kernel_Y_overflow\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_unsupported(void) {
	__asm__ volatile (
		"mov x0, x1\n\t"
		"mov x1, x2\n\t"
		"b kernel_Y_unsupported\n\t"
	);
}
static void __attribute__((naked)) calltable_adapter_Y_zero_div(void) {
	__asm__ volatile (
		"mov x5, x2\n\t"          /* x5 = Wptr */
		"ldr x9, [x1, #8]\n\t"    /* x9 = cparam[0] */
		"ldr x10, [x1, #16]\n\t"  /* x10 = cparam[1] */
		"ldr x11, [x1, #24]\n\t"  /* x11 = cparam[2] */
		"mov x4, x1\n\t"          /* x4 = sched */
		"mov x1, x9\n\t"          /* x1 = cparam[0] */
		"mov x2, x10\n\t"         /* x2 = cparam[1] */
		"mov x3, x11\n\t"         /* x3 = cparam[2] */
		"b kernel_Y_zero_div\n\t"
	);
}
#else /* !__aarch64__ */
/* Non-AArch64: use C adapters (x64/i386 don't have the LR issue) */
static word __attribute__((noinline)) calltable_adapter_X_malloc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_malloc(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_mrelease(word param0, sched_t *sched, word *Wptr) {
	kernel_X_mrelease(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_in(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_in(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_out(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_out(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_mt_alloc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_mt_alloc(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_mt_clone(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_mt_clone(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_mt_release(word param0, sched_t *sched, word *Wptr) {
	kernel_X_mt_release(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_in32(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_in32(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_in8(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_in8(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_in(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_in(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_out(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_out(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_xchg(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_xchg(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_xin(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_xin(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_xout(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_xout(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_xxchg(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_xxchg(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_out32(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_out32(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_out8(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_out8(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_outbyte(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_outbyte(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_outword(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_outword(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_fbar_enroll(word param0, sched_t *sched, word *Wptr) {
	kernel_X_fbar_enroll(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_fbar_init(word param0, sched_t *sched, word *Wptr) {
	kernel_X_fbar_init(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_fbar_resign(word param0, sched_t *sched, word *Wptr) {
	kernel_X_fbar_resign(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_ldtimer(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_ldtimer(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_mt_unlock(word param0, sched_t *sched, word *Wptr) {
	kernel_X_mt_unlock(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_proc_alloc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_proc_alloc(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_proc_mt_copy(word param0, sched_t *sched, word *Wptr) {
	kernel_X_proc_mt_copy(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_proc_mt_move(word param0, sched_t *sched, word *Wptr) {
	kernel_X_proc_mt_move(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_proc_param(word param0, sched_t *sched, word *Wptr) {
	kernel_X_proc_param(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_sem_release(word param0, sched_t *sched, word *Wptr) {
	kernel_X_sem_release(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_endp(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_endp(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_fbar_sync(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_fbar_sync(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mreleasep(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mreleasep(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_lock(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_lock(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mt_sync(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mt_sync(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_proc_end(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_proc_end(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_proc_start(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_proc_start(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_sem_claim(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_sem_claim(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_startp(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_startp(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_xin(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_xin(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_cdisc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_cdisc(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_cenbc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_cenbc(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_disc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_disc(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_enbc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_enbc(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_getpas(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_getpas(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_mt_enroll(word param0, sched_t *sched, word *Wptr) {
	kernel_X_mt_enroll(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_mt_resign(word param0, sched_t *sched, word *Wptr) {
	kernel_X_mt_resign(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_ndisc(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_ndisc(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_runp(word param0, sched_t *sched, word *Wptr) {
	kernel_X_runp(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_enbc2(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_enbc2(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_Y_enbc3(word param0, sched_t *sched, word *Wptr) {
	return kernel_Y_enbc3(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_fasttin(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_fasttin(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_pause(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_pause(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_stopp(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_stopp(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_tin(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_tin(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_alt(word param0, sched_t *sched, word *Wptr) {
	kernel_X_alt(sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_cdist(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_cdist(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_cenbt(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_cenbt(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_dist(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_dist(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_enbt(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_enbt(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_ndist(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_ndist(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_sem_init(word param0, sched_t *sched, word *Wptr) {
	kernel_X_sem_init(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_talt(word param0, sched_t *sched, word *Wptr) {
	kernel_X_talt(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_xend(word param0, sched_t *sched, word *Wptr) {
	kernel_X_xend(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_altend(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_altend(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_altwt(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_altwt(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_caltend(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_caltend(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_enbt2(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_enbt2(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_Y_enbt3(word param0, sched_t *sched, word *Wptr) {
	return kernel_Y_enbt3(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_taltwt(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_taltwt(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_xable(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_xable(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_cdiss(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_cdiss(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_cenbs(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_cenbs(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_diss(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_diss(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_enbs(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_enbs(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_mt_dclone(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_mt_dclone(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_ndiss(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_ndiss(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_enbs2(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_enbs2(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_Y_enbs3(word param0, sched_t *sched, word *Wptr) {
	return kernel_Y_enbs3(param0, sched->cparam[0], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_fmul(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_fmul(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_kernel_run(word param0, sched_t *sched, word *Wptr) {
	kernel_X_kernel_run(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_mt_bind(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_mt_bind(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_mt_resize(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_mt_resize(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_norm(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_norm(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_par_enroll(word param0, sched_t *sched, word *Wptr) {
	kernel_X_par_enroll(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_fastscheduler(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_fastscheduler(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_occscheduler(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_occscheduler(sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_getaff(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_getaff(sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_getpri(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_getpri(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_setaff(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_setaff(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_setpri(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_setpri(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_bx_kill(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_bx_kill(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_mppclone(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_mppclone(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_b_dispatch(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_b_dispatch(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_bx_dispatch(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_bx_dispatch(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mppdeserialise(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mppdeserialise(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_mppserialise(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_mppserialise(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_rtthreadinit(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_rtthreadinit(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_shutdown(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_shutdown(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_ldwsmap(word param0, sched_t *sched, word *Wptr) {
	kernel_X_ldwsmap(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_rmwsmap(word param0, sched_t *sched, word *Wptr) {
	kernel_X_rmwsmap(param0, sched, Wptr);
}
static word __attribute__((noinline)) calltable_adapter_X_trap(word param0, sched_t *sched, word *Wptr) {
	return kernel_X_trap(param0, sched->cparam[0], sched->cparam[1], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_X_ulwsmap(word param0, sched_t *sched, word *Wptr) {
	kernel_X_ulwsmap(param0, sched->cparam[0], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_BNSeterr(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_BNSeterr(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_BSeterr(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_BSeterr(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_BasicRangeError(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_BasicRangeError(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_RangeCheckError(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_RangeCheckError(param0, sched->cparam[0], sched->cparam[1], sched->cparam[2], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_Seterr(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_Seterr(param0, sched->cparam[0], sched->cparam[1], sched->cparam[2], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_dynproc_exit(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_dynproc_exit(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_dynproc_suspend(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_dynproc_suspend(param0, sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_floaterr(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_floaterr(param0, sched->cparam[0], sched->cparam[1], sched->cparam[2], sched->cparam[3], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_overflow(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_overflow(param0, sched->cparam[0], sched->cparam[1], sched->cparam[2], sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_unsupported(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_unsupported(sched, Wptr);
}
static void __attribute__((noinline)) calltable_adapter_Y_zero_div(word param0, sched_t *sched, word *Wptr) {
	kernel_Y_zero_div(param0, sched->cparam[0], sched->cparam[1], sched->cparam[2], sched, Wptr);
}
#endif /* __aarch64__ */
#define K_CALLTABLE_PTR(X) ((void *)(calltable_adapter_##X))
#else /* !CCSP_DIRECT_CALL */
#define K_CALLTABLE_PTR(X) K_CALL_PTR(X)
#endif /* CCSP_DIRECT_CALL */

static inline void build_calltable (void **table)
{
	/* X_malloc */
	table[  0] = K_CALLTABLE_PTR (X_malloc);
	/* X_mrelease */
	table[  1] = K_CALLTABLE_PTR (X_mrelease);
	/* Y_in */
	table[  2] = K_CALLTABLE_PTR (Y_in);
	/* Y_out */
	table[  3] = K_CALLTABLE_PTR (Y_out);
	/* X_mt_alloc */
	table[  4] = K_CALLTABLE_PTR (X_mt_alloc);
	/* X_mt_clone */
	table[  5] = K_CALLTABLE_PTR (X_mt_clone);
	/* X_mt_release */
	table[  6] = K_CALLTABLE_PTR (X_mt_release);
	/* Y_in32 */
	table[  7] = K_CALLTABLE_PTR (Y_in32);
	/* Y_in8 */
	table[  8] = K_CALLTABLE_PTR (Y_in8);
	/* Y_mt_in */
	table[  9] = K_CALLTABLE_PTR (Y_mt_in);
	/* Y_mt_out */
	table[ 10] = K_CALLTABLE_PTR (Y_mt_out);
	/* Y_mt_xchg */
	table[ 11] = K_CALLTABLE_PTR (Y_mt_xchg);
	/* Y_mt_xin */
	table[ 12] = K_CALLTABLE_PTR (Y_mt_xin);
	/* Y_mt_xout */
	table[ 13] = K_CALLTABLE_PTR (Y_mt_xout);
	/* Y_mt_xxchg */
	table[ 14] = K_CALLTABLE_PTR (Y_mt_xxchg);
	/* Y_out32 */
	table[ 15] = K_CALLTABLE_PTR (Y_out32);
	/* Y_out8 */
	table[ 16] = K_CALLTABLE_PTR (Y_out8);
	/* Y_outbyte */
	table[ 17] = K_CALLTABLE_PTR (Y_outbyte);
	/* Y_outword */
	table[ 18] = K_CALLTABLE_PTR (Y_outword);
	/* X_fbar_enroll */
	table[ 19] = K_CALLTABLE_PTR (X_fbar_enroll);
	/* X_fbar_init */
	table[ 20] = K_CALLTABLE_PTR (X_fbar_init);
	/* X_fbar_resign */
	table[ 21] = K_CALLTABLE_PTR (X_fbar_resign);
	/* X_ldtimer */
	table[ 22] = K_CALLTABLE_PTR (X_ldtimer);
	/* X_mt_unlock */
	table[ 23] = K_CALLTABLE_PTR (X_mt_unlock);
	/* X_proc_alloc */
	table[ 24] = K_CALLTABLE_PTR (X_proc_alloc);
	/* X_proc_mt_copy */
	table[ 25] = K_CALLTABLE_PTR (X_proc_mt_copy);
	/* X_proc_mt_move */
	table[ 26] = K_CALLTABLE_PTR (X_proc_mt_move);
	/* X_proc_param */
	table[ 27] = K_CALLTABLE_PTR (X_proc_param);
	/* X_sem_release */
	table[ 28] = K_CALLTABLE_PTR (X_sem_release);
	/* Y_endp */
	table[ 29] = K_CALLTABLE_PTR (Y_endp);
	/* Y_fbar_sync */
	table[ 30] = K_CALLTABLE_PTR (Y_fbar_sync);
	/* Y_mreleasep */
	table[ 31] = K_CALLTABLE_PTR (Y_mreleasep);
	/* Y_mt_lock */
	table[ 32] = K_CALLTABLE_PTR (Y_mt_lock);
	/* Y_mt_sync */
	table[ 33] = K_CALLTABLE_PTR (Y_mt_sync);
	/* Y_proc_end */
	table[ 34] = K_CALLTABLE_PTR (Y_proc_end);
	/* Y_proc_start */
	table[ 35] = K_CALLTABLE_PTR (Y_proc_start);
	/* Y_sem_claim */
	table[ 36] = K_CALLTABLE_PTR (Y_sem_claim);
	/* Y_startp */
	table[ 37] = K_CALLTABLE_PTR (Y_startp);
	/* Y_xin */
	table[ 38] = K_CALLTABLE_PTR (Y_xin);
	/* X_cdisc */
	table[ 39] = K_CALLTABLE_PTR (X_cdisc);
	/* X_cenbc */
	table[ 40] = K_CALLTABLE_PTR (X_cenbc);
	/* X_disc */
	table[ 41] = K_CALLTABLE_PTR (X_disc);
	/* X_enbc */
	table[ 42] = K_CALLTABLE_PTR (X_enbc);
	/* X_getpas */
	table[ 43] = K_CALLTABLE_PTR (X_getpas);
	/* X_mt_enroll */
	table[ 44] = K_CALLTABLE_PTR (X_mt_enroll);
	/* X_mt_resign */
	table[ 45] = K_CALLTABLE_PTR (X_mt_resign);
	/* X_ndisc */
	table[ 46] = K_CALLTABLE_PTR (X_ndisc);
	/* X_runp */
	table[ 47] = K_CALLTABLE_PTR (X_runp);
	/* Y_enbc2 */
	table[ 48] = K_CALLTABLE_PTR (Y_enbc2);
	/* Y_enbc3 */
	table[ 49] = K_CALLTABLE_PTR (Y_enbc3);
	/* Y_fasttin */
	table[ 50] = K_CALLTABLE_PTR (Y_fasttin);
	/* Y_pause */
	table[ 51] = K_CALLTABLE_PTR (Y_pause);
	/* Y_stopp */
	table[ 52] = K_CALLTABLE_PTR (Y_stopp);
	/* Y_tin */
	table[ 53] = K_CALLTABLE_PTR (Y_tin);
	/* X_alt */
	table[ 54] = K_CALLTABLE_PTR (X_alt);
	/* X_cdist */
	table[ 55] = K_CALLTABLE_PTR (X_cdist);
	/* X_cenbt */
	table[ 56] = K_CALLTABLE_PTR (X_cenbt);
	/* X_dist */
	table[ 57] = K_CALLTABLE_PTR (X_dist);
	/* X_enbt */
	table[ 58] = K_CALLTABLE_PTR (X_enbt);
	/* X_ndist */
	table[ 59] = K_CALLTABLE_PTR (X_ndist);
	/* X_sem_init */
	table[ 60] = K_CALLTABLE_PTR (X_sem_init);
	/* X_talt */
	table[ 61] = K_CALLTABLE_PTR (X_talt);
	/* X_xend */
	table[ 62] = K_CALLTABLE_PTR (X_xend);
	/* Y_altend */
	table[ 63] = K_CALLTABLE_PTR (Y_altend);
	/* Y_altwt */
	table[ 64] = K_CALLTABLE_PTR (Y_altwt);
	/* Y_caltend */
	table[ 65] = K_CALLTABLE_PTR (Y_caltend);
	/* Y_enbt2 */
	table[ 66] = K_CALLTABLE_PTR (Y_enbt2);
	/* Y_enbt3 */
	table[ 67] = K_CALLTABLE_PTR (Y_enbt3);
	/* Y_taltwt */
	table[ 68] = K_CALLTABLE_PTR (Y_taltwt);
	/* Y_xable */
	table[ 69] = K_CALLTABLE_PTR (Y_xable);
	/* X_cdiss */
	table[ 70] = K_CALLTABLE_PTR (X_cdiss);
	/* X_cenbs */
	table[ 71] = K_CALLTABLE_PTR (X_cenbs);
	/* X_diss */
	table[ 72] = K_CALLTABLE_PTR (X_diss);
	/* X_enbs */
	table[ 73] = K_CALLTABLE_PTR (X_enbs);
	/* X_mt_dclone */
	table[ 74] = K_CALLTABLE_PTR (X_mt_dclone);
	/* X_ndiss */
	table[ 75] = K_CALLTABLE_PTR (X_ndiss);
	/* Y_enbs2 */
	table[ 76] = K_CALLTABLE_PTR (Y_enbs2);
	/* Y_enbs3 */
	table[ 77] = K_CALLTABLE_PTR (Y_enbs3);
	/* X_fmul */
	table[ 78] = K_CALLTABLE_PTR (X_fmul);
	/* X_kernel_run */
	table[ 79] = K_CALLTABLE_PTR (X_kernel_run);
	/* X_mt_bind */
	table[ 80] = K_CALLTABLE_PTR (X_mt_bind);
	/* X_mt_resize */
	table[ 81] = K_CALLTABLE_PTR (X_mt_resize);
	/* X_norm */
	table[ 82] = K_CALLTABLE_PTR (X_norm);
	/* X_par_enroll */
	table[ 83] = K_CALLTABLE_PTR (X_par_enroll);
	/* Y_fastscheduler */
	table[ 84] = K_CALLTABLE_PTR (Y_fastscheduler);
	/* Y_occscheduler */
	table[ 85] = K_CALLTABLE_PTR (Y_occscheduler);
	/* Y_wait_int */
	table[ 86] = K_CALLTABLE_PTR (Y_unsupported);
	/* X_getaff */
	table[ 87] = K_CALLTABLE_PTR (X_getaff);
	/* X_getpri */
	table[ 88] = K_CALLTABLE_PTR (X_getpri);
	/* Y_setaff */
	table[ 89] = K_CALLTABLE_PTR (Y_setaff);
	/* Y_setpri */
	table[ 90] = K_CALLTABLE_PTR (Y_setpri);
	/* X_bx_kill */
	table[ 91] = K_CALLTABLE_PTR (X_bx_kill);
	/* X_mppclone */
	table[ 92] = K_CALLTABLE_PTR (X_mppclone);
	/* Y_b_dispatch */
	table[ 93] = K_CALLTABLE_PTR (Y_b_dispatch);
	/* Y_bx_dispatch */
	table[ 94] = K_CALLTABLE_PTR (Y_bx_dispatch);
	/* Y_mppdeserialise */
	table[ 95] = K_CALLTABLE_PTR (Y_mppdeserialise);
	/* Y_mppserialise */
	table[ 96] = K_CALLTABLE_PTR (Y_mppserialise);
	/* Y_rtthreadinit */
	table[ 97] = K_CALLTABLE_PTR (Y_rtthreadinit);
	/* Y_shutdown */
	table[ 98] = K_CALLTABLE_PTR (Y_shutdown);
	/* CIF_endp_resume_stub */
	table[ 99] = kernel_CIF_endp_resume_stub ();
	/* CIF_light_proc_stub */
	table[ 100] = kernel_CIF_light_proc_stub ();
	/* CIF_proc_stub */
	table[ 101] = kernel_CIF_proc_stub ();
	/* X_dtrace */
	table[ 102] = K_CALLTABLE_PTR (Y_unsupported);
	/* X_ldwsmap */
	table[ 103] = K_CALLTABLE_PTR (X_ldwsmap);
	/* X_rmwsmap */
	table[ 104] = K_CALLTABLE_PTR (X_rmwsmap);
	/* X_trap */
	table[ 105] = K_CALLTABLE_PTR (X_trap);
	/* X_ulwsmap */
	table[ 106] = K_CALLTABLE_PTR (X_ulwsmap);
	/* Y_BNSeterr */
	table[ 107] = K_CALLTABLE_PTR (Y_BNSeterr);
	/* Y_BSeterr */
	table[ 108] = K_CALLTABLE_PTR (Y_BSeterr);
	/* Y_BasicRangeError */
	table[ 109] = K_CALLTABLE_PTR (Y_BasicRangeError);
	/* Y_RangeCheckError */
	table[ 110] = K_CALLTABLE_PTR (Y_RangeCheckError);
	/* Y_Seterr */
	table[ 111] = K_CALLTABLE_PTR (Y_Seterr);
	/* Y_dynproc_exit */
	table[ 112] = K_CALLTABLE_PTR (Y_dynproc_exit);
	/* Y_dynproc_suspend */
	table[ 113] = K_CALLTABLE_PTR (Y_dynproc_suspend);
	/* Y_floaterr */
	table[ 114] = K_CALLTABLE_PTR (Y_floaterr);
	/* Y_overflow */
	table[ 115] = K_CALLTABLE_PTR (Y_overflow);
	/* Y_unsupported */
	table[ 116] = K_CALLTABLE_PTR (Y_unsupported);
	/* Y_zero_div */
	table[ 117] = K_CALLTABLE_PTR (Y_zero_div);
}


#endif /* !__CALLTABLE_H */

