/* ccsp_cif_stubs.h - generated by make-header.py; do not modify! */

#ifndef __CCSP_CIF_STUBS_H
#define __CCSP_CIF_STUBS_H

#define ccsp_cif_external_call(func, stack, result) \
	do { \
		word __tmp_sp; \
		__asm__ __volatile__ ("\n" \
			"	movq %%rsp, %0\n" \
			"	movq %2, %%rsp\n" \
			"	callq *%1\n" \
			"	movq %0, %%rsp\n" \
			: "=&r" (__tmp_sp), "=a" (result) \
			: "r" (func), "r" (stack) \
			: "cc", "memory", "rcx", "rdx", "rsi", "rdi", "r8", "r9", "r10", "r11" \
		); \
	} while (0)
#define ccsp_cif_jump(wptr, addr) \
	do { \
		__asm__ __volatile__ ("\n" \
			"	movq %0, %%r14\n" \
			"	jmpq *%1\n" \
			: /* no outputs */ \
			: "r" (wptr), "q" (addr) \
			: "memory" \
		); \
	} while (0)
#define ccsp_cif_occam_call(sched, stack, ws, func, top) \
	do { \
		register word __r_ws __asm__("rdi") = (word)(ws); \
		register word __r_sched __asm__("rsi") = (word)(sched); \
		register word __r_func __asm__("rax") = (word)(func); \
		register word __r_topoff __asm__("r8") = (word)(top * 8); \
		(void)(stack); \
		__asm__ __volatile__ ("\n" \
			"	movq %%rdi, %%r14\n" \
			"	addq %%r14, %%r8\n" \
			"	movq %%rsp, (%%r8)\n" \
			"	movq %%rbp, 8(%%r8)\n" \
			"	movq %%r8, 16(%%r8)\n" \
			"	leaq 0f(%%rip), %%r8\n" \
			"	movq %%r8, (%%r14)\n" \
			"	movq %%r8, -8(%%r14)\n" \
			"	leaq -256(%%r14), %%rsp\n" \
			"	andq $-16, %%rsp\n" \
			"	movq %%rsi, %%r15\n" \
			"	jmpq *%%rax\n" \
			"0:\n" \
			"	subq $32, %%r14\n" \
			"	addq %%r14, %3\n" \
			"	movq (%3), %%rsp\n" \
			"	movq 8(%3), %%rbp\n" \
			: "+r" (__r_ws), "+r" (__r_sched), "+r" (__r_func), "+r" (__r_topoff) \
			: /* no pure inputs */ \
			: "cc", "memory", \
			  "rcx", "rdx", "r9", "r10", "r11", \
			  "rbx", "r12", "r13", "r14", "r15" \
		); \
	} while (0)
#define ccsp_cif_X_malloc(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *48(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mrelease(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *56(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_in(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *64(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_out(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *72(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_mt_alloc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *80(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_clone(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *88(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_release(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *96(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_in32(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *104(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_in8(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *112(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_in(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *120(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_out(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *128(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xchg(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *136(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xin(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *144(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xout(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *152(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xxchg(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *160(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_out32(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *168(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_out8(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *176(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_outbyte(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *184(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_outword(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *192(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_fbar_enroll(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *200(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_fbar_init(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *208(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_fbar_resign(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *216(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_ldtimer(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *224(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_unlock(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *232(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_alloc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *240(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_mt_copy(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *248(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_mt_move(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *256(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_param(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *264(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_sem_release(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *272(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_endp(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *280(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_fbar_sync(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *288(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mreleasep(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *296(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_lock(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *304(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_sync(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *312(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_proc_end(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *320(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_proc_start(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *328(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_sem_claim(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *336(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_startp(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *344(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_xin(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *352(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_cdisc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *360(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_cenbc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *368(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_disc(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *376(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_enbc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *384(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_getpas(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *392(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_enroll(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *400(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_resign(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *408(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_ndisc(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *416(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_runp(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *424(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_enbc2(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *432(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_enbc3(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *440(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: "=a" (o0) \
			: "D" (i0) \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_fasttin(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *448(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_pause(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *456(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_stopp(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *464(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_tin(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *472(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_alt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *480(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11", "rax" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_cdist(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *488(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_cenbt(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *496(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_dist(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *504(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_enbt(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *512(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_ndist(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *520(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_sem_init(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *528(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_talt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *536(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11", "rax" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_xend(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *544(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_altend(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *552(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_altwt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *560(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_caltend(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *568(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_enbt2(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *576(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_enbt3(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *584(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: "=a" (o0) \
			: "D" (i0) \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_taltwt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *592(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_xable(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *600(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_cdiss(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *608(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_cenbs(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *616(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_diss(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *624(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_enbs(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *632(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_dclone(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *640(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_ndiss(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *648(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_enbs2(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *656(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_enbs3(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *664(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: "=a" (o0) \
			: "D" (i0) \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_X_fmul(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *672(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_kernel_run(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *680(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_bind(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *688(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_resize(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *696(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_norm(__wptr,i0,i1,o0,o1,o2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *704(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
			*((word *)(&(o1))) = __sched->cparam[0]; \
			*((word *)(&(o2))) = __sched->cparam[1]; \
		} \
	 } while (0)
#define ccsp_cif_X_par_enroll(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *712(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_fastscheduler(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *720(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_occscheduler(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *728(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_X_getaff(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *744(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_getpri(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *752(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_setaff(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *760(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_setpri(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *768(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_bx_kill(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *776(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_mppclone(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *784(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_b_dispatch(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *792(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_bx_dispatch(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *800(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mppdeserialise(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *808(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mppserialise(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *816(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_rtthreadinit(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *824(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_shutdown(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *832(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_CIF_endp_resume_stub(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *840(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11", "rax" \
			); \
		} \
	 } while (0)
#define ccsp_cif_CIF_light_proc_stub(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *848(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11", "rax" \
			); \
		} \
	 } while (0)
#define ccsp_cif_CIF_proc_stub(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *856(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy) \
				: "D" (__wptr), "1" (__sched) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11", "rax" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_ldwsmap(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *872(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_rmwsmap(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *880(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_X_trap(__wptr,i0,i1,i2,o0,o1,o2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *888(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (o0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
			*((word *)(&(o1))) = __sched->cparam[0]; \
			*((word *)(&(o2))) = __sched->cparam[1]; \
		} \
	 } while (0)
#define ccsp_cif_X_ulwsmap(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			word dummy0; \
			word sched_dummy; \
			word wptr_dummy; \
			__asm__ __volatile__ ("\n" \
				"	movq %%rsp, %%rcx\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *896(%%rsi)\n" \
				"	movq %%rcx, %%rsp\n" \
				: "=d" (wptr_dummy), "=S" (sched_dummy), "=a" (dummy0) \
				: "D" (__wptr), "1" (__sched), "2" (i0) \
				: "cc", "memory", "rcx", "r8", "r9", "r10", "r11" \
			); \
		} \
	 } while (0)
#define ccsp_cif_Y_BNSeterr(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *904(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_BSeterr(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *912(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_BasicRangeError(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *920(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_RangeCheckError(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *928(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_Seterr(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *936(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_dynproc_exit(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *944(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_dynproc_suspend(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *952(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_floaterr(__wptr,i0,i1,i2,i3,i4) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		__sched->cparam[3] = (word) (i4); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *960(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_overflow(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *968(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_unsupported(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__asm__ __volatile__ ("\n" \
			"	pushq %%rbp\n" \
			"	pushq %%rbx\n" \
			"	pushq %%r12\n" \
			"	pushq %%r13\n" \
			"	pushq %%r14\n" \
			"	movq %%rsp, -56(%%r14)\n" \
			"	movq (%%r15), %%rsp\n" \
			"	movq %%r15, %%rsi\n" \
			"	movq %%r14, %%rdx\n" \
			"	callq *976(%%r15)\n" \
			"	movq -56(%%r14), %%rsp\n" \
			"	popq %%r14\n" \
			"	popq %%r13\n" \
			"	popq %%r12\n" \
			"	popq %%rbx\n" \
			"	popq %%rbp\n" \
			: /* no outputs */ \
			: /* no inputs */ \
			: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11", "rax" \
		); \
		(__wptr)[SchedPtr] = (word) __sched; \
	 } while (0)
#define ccsp_cif_Y_zero_div(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			word dummy0; \
			__asm__ __volatile__ ("\n" \
				"	pushq %%rbp\n" \
				"	pushq %%rbx\n" \
				"	pushq %%r12\n" \
				"	pushq %%r13\n" \
				"	pushq %%r14\n" \
				"	movq %%rsp, -56(%%r14)\n" \
				"	movq (%%r15), %%rsp\n" \
				"	movq %%r15, %%rsi\n" \
				"	movq %%r14, %%rdx\n" \
				"	callq *984(%%r15)\n" \
				"	movq -56(%%r14), %%rsp\n" \
				"	popq %%r14\n" \
				"	popq %%r13\n" \
				"	popq %%r12\n" \
				"	popq %%rbx\n" \
				"	popq %%rbp\n" \
				: "=a" (dummy0) \
				: "D" (i0) \
				: "cc", "memory", "rcx", "rdx", "rsi", "r8", "r9", "r10", "r11" \
			); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)

#endif /* !__CCSP_CIF_STUBS_H */

