/* ccsp_cif_stubs.h - generated by make-header.py; do not modify! */

#ifndef __CCSP_CIF_STUBS_H
#define __CCSP_CIF_STUBS_H

#define ccsp_cif_external_call(func, stack, result) \
	do { \
		word __tmp_sp; \
		__asm__ __volatile__ ("\n" \
			"	movq %%rsp, %0\n" \
			"	movq %3, %%rsp\n" \
			"	callq *%2\n" \
			"	movq %0, %%rsp\n" \
			: "=&r" (__tmp_sp), "=a" (result) \
			: "r" (func), "r" (stack) \
			: "cc", "memory", "rcx", "rdx", "rsi", "rdi", "r8", "r9", "r10", "r11" \
		); \
	} while (0)
#define ccsp_cif_jump(wptr, addr) \
	do { \
		__asm__ __volatile__ ("\n" \
			"	movq %0, %%r14\n" \
			"	jmpq *%1\n" \
			: /* no outputs */ \
			: "r" (wptr), "q" (addr) \
			: "memory" \
		); \
	} while (0)
#define ccsp_cif_occam_call(sched, stack, ws, func, top) \
	do { \
		register word __r_ws __asm__("rdi") = (word)(ws); \
		register word __r_sched __asm__("rsi") = (word)(sched); \
		register word __r_func __asm__("rax") = (word)(func); \
		register word __r_topoff __asm__("r8") = (word)(top * 8); \
		(void)(stack); \
		__asm__ __volatile__ ("\n" \
			"	movq %%rdi, %%r14\n" \
			"	addq %%r14, %%r8\n" \
			"	movq %%rsp, (%%r8)\n" \
			"	movq %%rbp, 8(%%r8)\n" \
			"	movq %%r8, 16(%%r8)\n" \
			"	leaq 0f(%%rip), %%r8\n" \
			"	movq %%r8, (%%r14)\n" \
			"	movq %%r8, -8(%%r14)\n" \
			"	leaq -256(%%r14), %%rsp\n" \
			"	andq $-16, %%rsp\n" \
			"	movq %%rsi, %%r15\n" \
			"	jmpq *%%rax\n" \
			"0:\n" \
			"	subq $32, %%r14\n" \
			"	movq %4, %%r8\n" \
			"	addq %%r14, %%r8\n" \
			"	movq (%%r8), %%rsp\n" \
			"	movq 8(%%r8), %%rbp\n" \
			: "+r" (__r_ws), "+r" (__r_sched), "+r" (__r_func), "+r" (__r_topoff) \
			: "i" ((word)(top * 8)) \
			: "cc", "memory", \
			  "rcx", "rdx", "r9", "r10", "r11", \
			  "rbx", "r12", "r13", "r14", "r15" \
		); \
	} while (0)
#define ccsp_cif_X_malloc(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 48); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mrelease(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 56); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_in(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 64); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_out(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 72); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_mt_alloc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 80); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_clone(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 88); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_release(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 96); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_in32(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 104); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_in8(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 112); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_in(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 120); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_out(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 128); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xchg(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 136); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xin(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 144); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xout(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 152); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_xxchg(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 160); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_out32(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 168); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_out8(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 176); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_outbyte(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 184); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_outword(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 192); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_fbar_enroll(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 200); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_fbar_init(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 208); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_fbar_resign(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 216); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_ldtimer(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 224); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_unlock(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 232); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_alloc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 240); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_mt_copy(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 248); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_mt_move(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 256); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_proc_param(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 264); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_sem_release(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 272); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_endp(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 280); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_fbar_sync(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 288); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mreleasep(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 296); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_lock(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 304); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mt_sync(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 312); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_proc_end(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 320); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_proc_start(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 328); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_sem_claim(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 336); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_startp(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 344); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_xin(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 352); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_cdisc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 360); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_cenbc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 368); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_disc(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 376); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_enbc(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 384); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_getpas(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 392); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_enroll(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 400); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_resign(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 408); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_ndisc(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 416); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_runp(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 424); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_enbc2(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 432); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_enbc3(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 440); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_fasttin(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 448); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_pause(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 456); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_stopp(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 464); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_tin(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 472); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_alt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 480); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_cdist(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 488); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_cenbt(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 496); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_dist(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 504); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_enbt(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 512); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_ndist(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 520); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_sem_init(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 528); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_talt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 536); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_xend(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 544); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_altend(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 552); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_altwt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 560); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_caltend(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 568); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_enbt2(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 576); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_enbt3(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 584); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_taltwt(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 592); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_xable(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 600); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_cdiss(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 608); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_cenbs(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 616); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_diss(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 624); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_enbs(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 632); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_dclone(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 640); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_ndiss(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 648); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_enbs2(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 656); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_enbs3(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 664); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_fmul(__wptr,i0,i1,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 672); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_kernel_run(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 680); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_bind(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 688); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mt_resize(__wptr,i0,i1,i2,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 696); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_norm(__wptr,i0,i1,o0,o1,o2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 704); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			*((word *)(&(o1))) = __sched->cparam[0]; \
			*((word *)(&(o2))) = __sched->cparam[1]; \
		} \
	 } while (0)
#define ccsp_cif_X_par_enroll(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 712); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_fastscheduler(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 720); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_occscheduler(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 728); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_getaff(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 744); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_getpri(__wptr,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 752); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_setaff(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 760); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_setpri(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 768); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_X_bx_kill(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 776); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_mppclone(__wptr,i0,o0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 784); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_b_dispatch(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 792); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_bx_dispatch(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 800); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mppdeserialise(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 808); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_mppserialise(__wptr,i0,i1,i2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 816); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_rtthreadinit(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 824); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_shutdown(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 832); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_CIF_endp_resume_stub(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 840); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_CIF_light_proc_stub(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 848); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_CIF_proc_stub(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 856); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_ldwsmap(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 872); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_rmwsmap(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 880); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_X_trap(__wptr,i0,i1,i2,o0,o1,o2) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 888); \
			o0 = (__typeof__(o0)) ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			*((word *)(&(o1))) = __sched->cparam[0]; \
			*((word *)(&(o2))) = __sched->cparam[1]; \
		} \
	 } while (0)
#define ccsp_cif_X_ulwsmap(__wptr,i0,i1) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		{ \
			extern word ccsp_cif_x64_kcall(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 896); \
			ccsp_cif_x64_kcall((void *)__wptr, (void *)__sched, (word)(i0), __func); \
		} \
	 } while (0)
#define ccsp_cif_Y_BNSeterr(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 904); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_BSeterr(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 912); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_BasicRangeError(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 920); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_RangeCheckError(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 928); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_Seterr(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 936); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_dynproc_exit(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 944); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_dynproc_suspend(__wptr,i0) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 952); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_floaterr(__wptr,i0,i1,i2,i3,i4) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		__sched->cparam[3] = (word) (i4); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 960); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_overflow(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 968); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_unsupported(__wptr) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 976); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)
#define ccsp_cif_Y_zero_div(__wptr,i0,i1,i2,i3) \
	do { \
		ccsp_sched_t *__sched = (ccsp_sched_t *) ((__wptr)[SchedPtr]); \
		__sched->cparam[0] = (word) (i1); \
		__sched->cparam[1] = (word) (i2); \
		__sched->cparam[2] = (word) (i3); \
		{ \
			extern word ccsp_cif_x64_kcall_resched(void *, void *, word, void *); \
			void *__func = *(void **)((char *)__sched + 984); \
			ccsp_cif_x64_kcall_resched((void *)__wptr, (void *)__sched, (word)(i0), __func); \
			(__wptr)[SchedPtr] = (word) __sched; \
		} \
	 } while (0)

#endif /* !__CCSP_CIF_STUBS_H */

