/* kitable.h - generated by make-header.py; do not modify! */
/* WARNING: if you regenerate this file, tranx86 and libraries must be rebuilt */

#ifndef __KITABLE_H
#define __KITABLE_H

#define K_MALLOC 0
#define K_MRELEASE 1
#define K_IN 2
#define K_OUT 3
#define K_MT_ALLOC 4
#define K_MT_CLONE 5
#define K_MT_RELEASE 6
#define K_IN32 7
#define K_IN8 8
#define K_MT_IN 9
#define K_MT_OUT 10
#define K_MT_XCHG 11
#define K_MT_XIN 12
#define K_MT_XOUT 13
#define K_MT_XXCHG 14
#define K_OUT32 15
#define K_OUT8 16
#define K_OUTBYTE 17
#define K_OUTWORD 18
#define K_FBAR_ENROLL 19
#define K_FBAR_INIT 20
#define K_FBAR_RESIGN 21
#define K_LDTIMER 22
#define K_MT_UNLOCK 23
#define K_PROC_ALLOC 24
#define K_PROC_MT_COPY 25
#define K_PROC_MT_MOVE 26
#define K_PROC_PARAM 27
#define K_SEM_RELEASE 28
#define K_ENDP 29
#define K_FBAR_SYNC 30
#define K_MRELEASEP 31
#define K_MT_LOCK 32
#define K_MT_SYNC 33
#define K_PROC_END 34
#define K_PROC_START 35
#define K_SEM_CLAIM 36
#define K_STARTP 37
#define K_XIN 38
#define K_CDISC 39
#define K_CENBC 40
#define K_DISC 41
#define K_ENBC 42
#define K_GETPAS 43
#define K_MT_ENROLL 44
#define K_MT_RESIGN 45
#define K_NDISC 46
#define K_RUNP 47
#define K_ENBC2 48
#define K_ENBC3 49
#define K_FASTTIN 50
#define K_PAUSE 51
#define K_STOPP 52
#define K_TIN 53
#define K_ALT 54
#define K_CDIST 55
#define K_CENBT 56
#define K_DIST 57
#define K_ENBT 58
#define K_NDIST 59
#define K_SEM_INIT 60
#define K_TALT 61
#define K_XEND 62
#define K_ALTEND 63
#define K_ALTWT 64
#define K_CALTEND 65
#define K_ENBT2 66
#define K_ENBT3 67
#define K_TALTWT 68
#define K_XABLE 69
#define K_CDISS 70
#define K_CENBS 71
#define K_DISS 72
#define K_ENBS 73
#define K_MT_DCLONE 74
#define K_NDISS 75
#define K_ENBS2 76
#define K_ENBS3 77
#define K_FMUL 78
#define K_KERNEL_RUN 79
#define K_MT_BIND 80
#define K_MT_RESIZE 81
#define K_NORM 82
#define K_PAR_ENROLL 83
#define K_FASTSCHEDULER 84
#define K_OCCSCHEDULER 85
#define K_WAIT_INT 86
#define K_GETAFF 87
#define K_GETPRI 88
#define K_SETAFF 89
#define K_SETPRI 90
#define K_BX_KILL 91
#define K_MPPCLONE 92
#define K_B_DISPATCH 93
#define K_BX_DISPATCH 94
#define K_MPPDESERIALISE 95
#define K_MPPSERIALISE 96
#define K_RTTHREADINIT 97
#define K_SHUTDOWN 98
#define K_CIF_ENDP_RESUME_STUB 99
#define K_CIF_LIGHT_PROC_STUB 100
#define K_CIF_PROC_STUB 101
#define K_DTRACE 102
#define K_LDWSMAP 103
#define K_RMWSMAP 104
#define K_TRAP 105
#define K_ULWSMAP 106
#define K_BNSETERR 107
#define K_BSETERR 108
#define K_BRANGERR 109
#define K_RANGERR 110
#define K_SETERR 111
#define K_DYNPROC_EXIT 112
#define K_DYNPROC_SUSPEND 113
#define K_FLOATERR 114
#define K_OVERFLOW 115
#define K_UNSUPPORTED 116
#define K_UNPACKSN K_UNSUPPORTED
#define K_POSTNORMSN K_UNSUPPORTED
#define K_ROUNDSN K_UNSUPPORTED
#define K_SAVEL K_UNSUPPORTED
#define K_STLB K_UNSUPPORTED
#define K_STLF K_UNSUPPORTED
#define K_RES_RELEASE K_UNSUPPORTED
#define K_RES_CLAIM K_UNSUPPORTED
#define K_MNEW K_UNSUPPORTED
#define K_MFREE K_UNSUPPORTED
#define K_EXTIN K_UNSUPPORTED
#define K_EXTOUT K_UNSUPPORTED
#define K_EXTVRFY K_UNSUPPORTED
#define K_EXTIN8 K_UNSUPPORTED
#define K_EXTIN32 K_UNSUPPORTED
#define K_EXTOUT8 K_UNSUPPORTED
#define K_EXTOUT32 K_UNSUPPORTED
#define K_EXTOUTBYTE K_UNSUPPORTED
#define K_EXTOUTWORD K_UNSUPPORTED
#define K_EXTENBC K_UNSUPPORTED
#define K_EXTNDISC K_UNSUPPORTED
#define K_EXTMIN K_UNSUPPORTED
#define K_EXTMIN64 K_UNSUPPORTED
#define K_EXTMOUT K_UNSUPPORTED
#define K_EXTMOUT64 K_UNSUPPORTED
#define K_EXTMINN K_UNSUPPORTED
#define K_EXTMOUTN K_UNSUPPORTED
#define K_SAVEPRI K_UNSUPPORTED
#define K_STPRIF K_UNSUPPORTED
#define K_STPRIB K_UNSUPPORTED
#define K_MWENB K_UNSUPPORTED
#define K_MWDIS K_UNSUPPORTED
#define K_MWALTWT K_UNSUPPORTED
#define K_MWALT K_UNSUPPORTED
#define K_MWALTEND K_UNSUPPORTED
#define K_FASTIN8 K_UNSUPPORTED
#define K_FASTIN32 K_UNSUPPORTED
#define K_FASTIN K_UNSUPPORTED
#define K_FASTOUT8 K_UNSUPPORTED
#define K_FASTOUT32 K_UNSUPPORTED
#define K_FASTOUT K_UNSUPPORTED
#define K_MWS_BINIT K_UNSUPPORTED
#define K_MWS_PBRILNK K_UNSUPPORTED
#define K_MWS_PBRULNK K_UNSUPPORTED
#define K_MWS_PPILNK K_UNSUPPORTED
#define K_MWS_PBENROLL K_UNSUPPORTED
#define K_MWS_PBRESIGN K_UNSUPPORTED
#define K_MWS_PBADJSYNC K_UNSUPPORTED
#define K_MWS_SYNC K_UNSUPPORTED
#define K_MWS_ALTLOCK K_UNSUPPORTED
#define K_MWS_ALTUNLOCK K_UNSUPPORTED
#define K_MWS_ALT K_UNSUPPORTED
#define K_MWS_ALTEND K_UNSUPPORTED
#define K_MWS_ENB K_UNSUPPORTED
#define K_MWS_DIS K_UNSUPPORTED
#define K_MWS_ALTPOSTLOCK K_UNSUPPORTED
#define K_MWS_PPBASEOF K_UNSUPPORTED
#define K_MWS_PPPAROF K_UNSUPPORTED
#define K_MIN K_UNSUPPORTED
#define K_MOUT K_UNSUPPORTED
#define K_MIN64 K_UNSUPPORTED
#define K_MOUT64 K_UNSUPPORTED
#define K_XMIN K_UNSUPPORTED
#define K_XMIN64 K_UNSUPPORTED
#define K_MINN K_UNSUPPORTED
#define K_MOUTN K_UNSUPPORTED
#define K_XMINN K_UNSUPPORTED
#define K_ZERODIV 117

#if !defined(__cplusplus)
#if defined(__GNUC__)
__attribute__ ((unused)) /* make GCC ignore when unused */
#endif
static ccsp_entrytype ccsp_entrytable[] = {
	{
	 .call_offset  = K_MALLOC,
	 .entrypoint   = "X_malloc",
	 .input        = 1,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MRELEASE,
	 .entrypoint   = "X_mrelease",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_IN,
	 .entrypoint   = "Y_in",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_OUT,
	 .entrypoint   = "Y_out",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_ALLOC,
	 .entrypoint   = "X_mt_alloc",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_CLONE,
	 .entrypoint   = "X_mt_clone",
	 .input        = 1,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_RELEASE,
	 .entrypoint   = "X_mt_release",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_IN32,
	 .entrypoint   = "Y_in32",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_IN8,
	 .entrypoint   = "Y_in8",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_IN,
	 .entrypoint   = "Y_mt_in",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_OUT,
	 .entrypoint   = "Y_mt_out",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_XCHG,
	 .entrypoint   = "Y_mt_xchg",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_XIN,
	 .entrypoint   = "Y_mt_xin",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_XOUT,
	 .entrypoint   = "Y_mt_xout",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_XXCHG,
	 .entrypoint   = "Y_mt_xxchg",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_OUT32,
	 .entrypoint   = "Y_out32",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_OUT8,
	 .entrypoint   = "Y_out8",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_OUTBYTE,
	 .entrypoint   = "Y_outbyte",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_OUTWORD,
	 .entrypoint   = "Y_outword",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FBAR_ENROLL,
	 .entrypoint   = "X_fbar_enroll",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FBAR_INIT,
	 .entrypoint   = "X_fbar_init",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FBAR_RESIGN,
	 .entrypoint   = "X_fbar_resign",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_LDTIMER,
	 .entrypoint   = "X_ldtimer",
	 .input        = 0,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_UNLOCK,
	 .entrypoint   = "X_mt_unlock",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PROC_ALLOC,
	 .entrypoint   = "X_proc_alloc",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PROC_MT_COPY,
	 .entrypoint   = "X_proc_mt_copy",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PROC_MT_MOVE,
	 .entrypoint   = "X_proc_mt_move",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PROC_PARAM,
	 .entrypoint   = "X_proc_param",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_SEM_RELEASE,
	 .entrypoint   = "X_sem_release",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENDP,
	 .entrypoint   = "Y_endp",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FBAR_SYNC,
	 .entrypoint   = "Y_fbar_sync",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MRELEASEP,
	 .entrypoint   = "Y_mreleasep",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_LOCK,
	 .entrypoint   = "Y_mt_lock",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_SYNC,
	 .entrypoint   = "Y_mt_sync",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PROC_END,
	 .entrypoint   = "Y_proc_end",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PROC_START,
	 .entrypoint   = "Y_proc_start",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_SEM_CLAIM,
	 .entrypoint   = "Y_sem_claim",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_STARTP,
	 .entrypoint   = "Y_startp",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_XIN,
	 .entrypoint   = "Y_xin",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CDISC,
	 .entrypoint   = "X_cdisc",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CENBC,
	 .entrypoint   = "X_cenbc",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_DISC,
	 .entrypoint   = "X_disc",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBC,
	 .entrypoint   = "X_enbc",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_GETPAS,
	 .entrypoint   = "X_getpas",
	 .input        = 0,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_ENROLL,
	 .entrypoint   = "X_mt_enroll",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_RESIGN,
	 .entrypoint   = "X_mt_resign",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_NDISC,
	 .entrypoint   = "X_ndisc",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_RUNP,
	 .entrypoint   = "X_runp",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBC2,
	 .entrypoint   = "Y_enbc2",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBC3,
	 .entrypoint   = "Y_enbc3",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FASTTIN,
	 .entrypoint   = "Y_fasttin",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PAUSE,
	 .entrypoint   = "Y_pause",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_STOPP,
	 .entrypoint   = "Y_stopp",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_TIN,
	 .entrypoint   = "Y_tin",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ALT,
	 .entrypoint   = "X_alt",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CDIST,
	 .entrypoint   = "X_cdist",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CENBT,
	 .entrypoint   = "X_cenbt",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_DIST,
	 .entrypoint   = "X_dist",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBT,
	 .entrypoint   = "X_enbt",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_NDIST,
	 .entrypoint   = "X_ndist",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_SEM_INIT,
	 .entrypoint   = "X_sem_init",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_TALT,
	 .entrypoint   = "X_talt",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_XEND,
	 .entrypoint   = "X_xend",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ALTEND,
	 .entrypoint   = "Y_altend",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ALTWT,
	 .entrypoint   = "Y_altwt",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CALTEND,
	 .entrypoint   = "Y_caltend",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBT2,
	 .entrypoint   = "Y_enbt2",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBT3,
	 .entrypoint   = "Y_enbt3",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_TALTWT,
	 .entrypoint   = "Y_taltwt",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_XABLE,
	 .entrypoint   = "Y_xable",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CDISS,
	 .entrypoint   = "X_cdiss",
	 .input        = 1,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CENBS,
	 .entrypoint   = "X_cenbs",
	 .input        = 1,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_DISS,
	 .entrypoint   = "X_diss",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBS,
	 .entrypoint   = "X_enbs",
	 .input        = 1,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_DCLONE,
	 .entrypoint   = "X_mt_dclone",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_NDISS,
	 .entrypoint   = "X_ndiss",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBS2,
	 .entrypoint   = "Y_enbs2",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ENBS3,
	 .entrypoint   = "Y_enbs3",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FMUL,
	 .entrypoint   = "X_fmul",
	 .input        = 2,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_KERNEL_RUN,
	 .entrypoint   = "X_kernel_run",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_BIND,
	 .entrypoint   = "X_mt_bind",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MT_RESIZE,
	 .entrypoint   = "X_mt_resize",
	 .input        = 3,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_NORM,
	 .entrypoint   = "X_norm",
	 .input        = 2,
	 .output       = 3,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_PAR_ENROLL,
	 .entrypoint   = "X_par_enroll",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FASTSCHEDULER,
	 .entrypoint   = "Y_fastscheduler",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_OCCSCHEDULER,
	 .entrypoint   = "Y_occscheduler",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_WAIT_INT,
	 .entrypoint   = "Y_wait_int",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_GETAFF,
	 .entrypoint   = "X_getaff",
	 .input        = 0,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_GETPRI,
	 .entrypoint   = "X_getpri",
	 .input        = 0,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_SETAFF,
	 .entrypoint   = "Y_setaff",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_SETPRI,
	 .entrypoint   = "Y_setpri",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_BX_KILL,
	 .entrypoint   = "X_bx_kill",
	 .input        = 1,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MPPCLONE,
	 .entrypoint   = "X_mppclone",
	 .input        = 1,
	 .output       = 1,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_B_DISPATCH,
	 .entrypoint   = "Y_b_dispatch",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_BX_DISPATCH,
	 .entrypoint   = "Y_bx_dispatch",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MPPDESERIALISE,
	 .entrypoint   = "Y_mppdeserialise",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_MPPSERIALISE,
	 .entrypoint   = "Y_mppserialise",
	 .input        = 3,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_RTTHREADINIT,
	 .entrypoint   = "Y_rtthreadinit",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_SHUTDOWN,
	 .entrypoint   = "Y_shutdown",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CIF_ENDP_RESUME_STUB,
	 .entrypoint   = "CIF_endp_resume_stub",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CIF_LIGHT_PROC_STUB,
	 .entrypoint   = "CIF_light_proc_stub",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_CIF_PROC_STUB,
	 .entrypoint   = "CIF_proc_stub",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_DTRACE,
	 .entrypoint   = "X_dtrace",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_LDWSMAP,
	 .entrypoint   = "X_ldwsmap",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_RMWSMAP,
	 .entrypoint   = "X_rmwsmap",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_TRAP,
	 .entrypoint   = "X_trap",
	 .input        = 3,
	 .output       = 3,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ULWSMAP,
	 .entrypoint   = "X_ulwsmap",
	 .input        = 2,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_BNSETERR,
	 .entrypoint   = "Y_BNSeterr",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_BSETERR,
	 .entrypoint   = "Y_BSeterr",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_BRANGERR,
	 .entrypoint   = "Y_BasicRangeError",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_RANGERR,
	 .entrypoint   = "Y_RangeCheckError",
	 .input        = 4,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_SETERR,
	 .entrypoint   = "Y_Seterr",
	 .input        = 4,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_DYNPROC_EXIT,
	 .entrypoint   = "Y_dynproc_exit",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_DYNPROC_SUSPEND,
	 .entrypoint   = "Y_dynproc_suspend",
	 .input        = 1,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_FLOATERR,
	 .entrypoint   = "Y_floaterr",
	 .input        = 5,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_OVERFLOW,
	 .entrypoint   = "Y_overflow",
	 .input        = 4,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_UNSUPPORTED,
	 .entrypoint   = "Y_unsupported",
	 .input        = 0,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
	{
	 .call_offset  = K_ZERODIV,
	 .entrypoint   = "Y_zero_div",
	 .input        = 4,
	 .output       = 0,
	 .support      = KCALL_SUPPORTED
	},
};
#endif /* !__cplusplus */

#endif /* !__KITABLE_H */

